### ISSUE TITLE
Rails 5: Deprecation Warning

### ISSUE THREAD

**Issue by michaelhodgejr** [curtis/honeypot-captcha#13]
Got the following warning after upgrading application to rails 5.0

DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using su
per. (called from module:FormTagHelper at /Users/user/.rvm/gems/ruby-2.3.1@gemset-rails5/bundler/gems/honeypot-captcha-94cea0485ad9/lib/h
oneypot-captcha/form_tag_helper.rb:18)

**Comment by kiote** [comment]
any plans to make this gem Rails 5 compatible?

**Comment by RandieM** [comment]
With Rails 5.1.2, I get the following and the server crashes.
`There was an error while trying to load the gem 'honeypot-captcha'. (Bundler::GemRequireError)
Gem Load Error is: undefined method 'alias_method_chain' for ActionView::Helpers::FormTagHelper:Module
Did you mean?  alias_method`

**Comment by RandieM** [comment]
I slightly adapted the "offending" code, so that this gem works in Rails 5.1.2, and started a merge request. My solution may not be optimal, but, for now, it solves the problem.

**Comment by sunny** [comment]
The mentioned merge request : #16

**Comment by curtis** [comment]
Fixed by #16
